import { test } from 'node:test';
import assert from 'node:assert/strict';
import { loadConfig } from '../scripts/lib/config.mjs';
import { scanFile } from '../scripts/lib/scan.mjs';

const cfg = loadConfig(process.cwd());
const scan = (file, text) => scanFile(file, text, cfg);
const rules = (file, text) => scan(file, text).map((v) => v.rule);
const find = (file, text, rule) => scan(file, text).find((v) => v.rule === rule);

test('flags a hardcoded hex that duplicates a token and suggests it', () => {
  const v = find('a.css', '.x{color:#2563EB}', 'rawHex');
  assert.ok(v, 'expected a rawHex violation');
  assert.equal(v.severity, 'error');
  assert.equal(v.fix, 'blue'); // #2563EB is the brand token in the starter
});

test('flags an off-palette hex with no token suggestion', () => {
  const v = find('a.css', '.x{color:#123456}', 'rawHex');
  assert.ok(v);
  assert.equal(v.fix, null);
});

test('flags rgba() literals', () => {
  assert.ok(rules('a.css', '.x{background:rgba(0,0,0,.5)}').includes('rawRgb'));
});

test('flags an off-system font family', () => {
  assert.ok(rules('a.css', '.x{font-family:Comic Sans MS}').includes('rawFont'));
});

test('allows tokens referenced via var(), $, tokens.* and {group.key} alias', () => {
  assert.equal(scan('a.css', '.x{color:var(--blue)}').length, 0);
  assert.equal(scan('a.css', '.x{font-family:{font.body}}').length, 0);
});

test('warns on spacing off the numeric scale, in style files only', () => {
  assert.ok(rules('a.css', '.x{padding:17px}').includes('offScaleSpacing'));
  // bare px in TSX is intentionally not flagged as spacing (too noisy)
  assert.ok(!rules('a.tsx', 'const s = "17px"').includes('offScaleSpacing'));
});

test('does not treat font-size px as off-scale spacing', () => {
  assert.ok(!rules('a.css', '.x{font-size:13px}').includes('offScaleSpacing'));
});

test('exempts the generated token file', () => {
  const gen = ':root{\n/* generated by `strap tokens` */\n--x:#123456;}';
  assert.equal(scan('tokens.css', gen).length, 0);
});

test('does NOT flag camelCase registry names as redefined components', () => {
  // starter registry has lowercase names (button, card...) -> PascalCase-only rule stays dormant
  assert.ok(!rules('x.tsx', 'const button = 1; function card(){}').includes('unlinkedComponent'));
});

test('respects allowlisted colors', () => {
  assert.equal(scan('a.css', '.x{color:transparent}').length, 0);
});

// --- duplicate radar (advisory) ---------------------------------------------
// The starter "card" component consumes color.line, color.white, radius.card, shadow.md.
const cardLookalike =
  '.panel{background:var(--white);border:1px solid var(--line);border-radius:var(--radius-card);box-shadow:var(--shadow-md)}';

test('flags a CSS rule that rebuilds a registry component (warn only)', () => {
  const v = find('a.css', cardLookalike, 'duplicateComponent');
  assert.ok(v, 'expected a duplicateComponent violation');
  assert.equal(v.severity, 'warn');
  assert.match(v.message, /"card"/);
});

test('does NOT flag the component\'s own named styles', () => {
  const own = cardLookalike.replace('.panel', '.card');
  assert.ok(!rules('a.css', own).includes('duplicateComponent'));
});

test('does NOT flag a rule that shares too few of a component\'s tokens', () => {
  // only one card token -> below the shared/coverage threshold
  assert.ok(!rules('a.css', '.thing{background:var(--white)}').includes('duplicateComponent'));
});

test('duplicate radar is CSS-only (not TSX, to avoid noise)', () => {
  assert.ok(!rules('a.tsx', cardLookalike).includes('duplicateComponent'));
});

test('duplicate radar is not fooled by a component name in a comment', () => {
  const withComment = '/* really a Card, honest */\n' + cardLookalike;
  assert.ok(rules('a.css', withComment).includes('duplicateComponent'));
});

test('duplicate radar can be turned off via config', () => {
  const off = { ...cfg, rules: { ...cfg.rules, duplicateComponent: 'off' } };
  assert.equal(scanFile('a.css', cardLookalike, off).filter((v) => v.rule === 'duplicateComponent').length, 0);
});
