// Strap importer: convert a design-tokens.json (DTCG-ish, {group.key} aliases) plus
// component spec files into the Strap artifacts (.strap/tokens.json + registry.json).
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';

const ALIAS_RE = /\{([a-zA-Z]+)\.([a-zA-Z0-9]+)\}/g;

function flattenColors(color) {
  const out = {};
  for (const [k, v] of Object.entries(color || {})) {
    if (typeof v === 'string') out[k] = v;
    else if (v && typeof v === 'object') {
      for (const [k2, v2] of Object.entries(v)) {
        if (typeof v2 === 'string') out[`${k}/${k2}`] = v2;
      }
    }
  }
  return out;
}

function numericScale(map) {
  const set = new Set();
  for (const v of Object.values(map || {})) {
    const n = parseFloat(String(v));
    if (!Number.isNaN(n)) set.add(n);
  }
  return [...set].sort((a, b) => a - b);
}

function fontFamilies(fontMap) {
  const fams = new Set();
  for (const stack of Object.values(fontMap || {})) {
    for (let part of String(stack).split(',')) {
      part = part.trim().replace(/^["']|["']$/g, '');
      if (part) fams.add(part);
    }
  }
  return [...fams];
}

export function importDesignSystem(root, sourceDir) {
  const srcDir = sourceDir || join(root, '.strap', 'source');
  const dtPath = join(srcDir, 'design-tokens.json');
  if (!existsSync(dtPath)) {
    throw new Error(`expected ${dtPath} — pass a source dir (\`strap import <dir>\`) or put design-tokens.json in .strap/source/.`);
  }
  const dt = JSON.parse(readFileSync(dtPath, 'utf8'));

  const colors = flattenColors(dt.color);
  const spacing = [...new Set([0, ...numericScale(dt.space)])].sort((a, b) => a - b);
  const radius = numericScale(dt.radius);

  const tokens = {
    _source: {
      origin: dt.$meta?.name || 'design-tokens.json',
      brand: dt.$meta?.brand || null,
      importedFrom: '.strap/source/design-tokens.json',
    },
    _note: 'Generated by `strap import` from .strap/source/. Edit the source + re-run, do not hand-edit.',
    colors,
    spacing,
    radius,
    radiusNamed: dt.radius || {},
    spaceNamed: dt.space || {},
    fonts: fontFamilies(dt.font),
    fontStacks: dt.font || {},
    shadows: dt.shadow || {},
    gradients: dt.gradient || {},
    motion: dt.motion || {},
    typography: dt.typography || {},
  };
  writeFileSync(join(root, '.strap', 'tokens.json'), JSON.stringify(tokens, null, 2) + '\n');

  // Registry from every components.*.json in the source dir.
  const components = [];
  for (const file of readdirSync(srcDir)) {
    if (!/^components\..*\.json$/.test(file)) continue;
    const data = JSON.parse(readFileSync(join(srcDir, file), 'utf8'));
    const layer = data.$meta?.name || file;
    for (const [name, spec] of Object.entries(data.components || {})) {
      const blob = JSON.stringify(spec);
      const refs = new Set();
      let m;
      ALIAS_RE.lastIndex = 0;
      while ((m = ALIAS_RE.exec(blob))) refs.add(`${m[1]}.${m[2]}`);
      components.push({
        name,
        source: `.strap/source/${file}`,
        layer,
        element: spec.element || null,
        description: spec.description || '',
        variants: spec.variants ? Object.keys(spec.variants) : spec.states ? Object.keys(spec.states) : [],
        consumes: [...refs].sort(),
      });
    }
  }
  writeFileSync(
    join(root, '.strap', 'registry.json'),
    JSON.stringify({ _note: 'Generated by `strap import`. Tier-3 component layer.', components }, null, 2) + '\n'
  );

  return { colorCount: Object.keys(colors).length, componentCount: components.length, spacing, radius };
}
