// Strap scaffold: the one "act" step — turns an approved promotion proposal into
// a token-bound STARTER component (a new .tsx + .css). It only creates new files;
// it never edits call-sites or deletes anything, so the human stays the editor.
// Pure (returns file contents); the command does the writing.

const GROUP_PREFIXED = new Set(['radius', 'shadow', 'gradient', 'motion', 'space', 'font']);
const kebab = (s) =>
  String(s).replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase();

// Canonical token key (`color.line`, `radius.card`) -> the CSS variable Strap
// generates for it (`--line`, `--radius-card`). Mirrors `strap tokens` naming.
export function tokenToCssVar(key) {
  const parts = String(key).split('.');
  const group = parts[0];
  const leaf = parts.slice(1).join('.');
  return GROUP_PREFIXED.has(group) ? `--${group}-${kebab(leaf)}` : `--${kebab(leaf)}`;
}

const pascal = (s) => String(s).replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_, __, c) => c.toUpperCase());

// Group tokens and, for colors, guess a role from the leaf name (advisory — the
// generated file is a starting point the human refines).
function plan(tokens) {
  const g = { color: [], radius: [], shadow: [], font: [], space: [], other: [] };
  for (const t of tokens) {
    const group = String(t).split('.')[0];
    (g[group] || g.other).push(t);
  }
  const borders = [], texts = [], surfaces = [];
  for (const t of g.color) {
    const leaf = String(t).split('.').slice(1).join('.').toLowerCase();
    if (/line|border|stroke|divider/.test(leaf)) borders.push(t);
    else if (/ink|text|fg|foreground|label|title/.test(leaf)) texts.push(t);
    else surfaces.push(t);
  }
  return { ...g, borders, texts, surfaces };
}

/**
 * @param {string} rawName  desired component name
 * @param {string[]} tokens canonical token keys from the promotion proposal
 * @returns {{name:string, className:string, files:Array<{ext:string, content:string}>, consumes:string[]}}
 */
export function scaffoldComponent(rawName, tokens) {
  const name = pascal(rawName) || 'NewComponent';
  const className = kebab(name);
  const p = plan(tokens);
  const v = (t) => `var(${tokenToCssVar(t)})`;

  const decls = [];
  if (p.surfaces[0]) decls.push(`  background: ${v(p.surfaces[0])};`);
  if (p.texts[0]) decls.push(`  color: ${v(p.texts[0])};`);
  if (p.borders[0]) decls.push(`  border: 1px solid ${v(p.borders[0])};`);
  if (p.radius[0]) decls.push(`  border-radius: ${v(p.radius[0])};`);
  if (p.shadow[0]) decls.push(`  box-shadow: ${v(p.shadow[0])};`);
  if (p.font[0]) decls.push(`  font-family: ${v(p.font[0])};`);
  if (p.space[0]) decls.push(`  padding: ${v(p.space[0])};`);
  // Any tokens not placed above — surfaced as a TODO so nothing is silently dropped.
  const placed = new Set([p.surfaces[0], p.texts[0], p.borders[0], p.radius[0], p.shadow[0], p.font[0], p.space[0]].filter(Boolean));
  const leftover = tokens.filter((t) => !placed.has(t));
  const todo = leftover.length ? `\n  /* TODO: also bind ${leftover.map(v).join(', ')} */` : '';

  const css = `/* Generated by \`strap scaffold\` from a promotion proposal — a token-bound
   starting point. Adjust which token maps to which property, then adopt it. */
.${className} {
${decls.join('\n')}${todo}
}
`;

  const tsx = `import './${name}.css';

// Generated by \`strap scaffold\` — a token-bound starting point. Refine props + markup.
export function ${name}({ children }: { children?: React.ReactNode }) {
  return <div className="${className}">{children}</div>;
}
`;

  return {
    name,
    className,
    consumes: [...tokens],
    files: [
      { ext: 'tsx', content: tsx },
      { ext: 'css', content: css },
    ],
  };
}
