// Strap scanner: the actual enforcement rules.
// Given file contents + config, return a list of violations.
import { normalizeHex } from './config.mjs';

const SEV_RANK = { off: 0, warn: 1, error: 2 };

function sev(cfg, rule) {
  return cfg.rules[rule] || 'off';
}

// Build a line index so byte offsets become line/col.
function locate(text, index) {
  let line = 1;
  let last = 0;
  for (let i = 0; i < index; i++) {
    if (text[i] === '\n') {
      line++;
      last = i + 1;
    }
  }
  return { line, col: index - last + 1 };
}

const HEX_RE = /#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b/g;
const RGB_RE = /\brgba?\(\s*[\d.]+[\s,]+[\d.]+[\s,]+[\d.]+(?:[\s,/]+[\d.%]+)?\s*\)/g;
const PX_RE = /\b(\d+(?:\.\d+)?)px\b/g;
const FONT_FAMILY_RE = /font-family\s*:\s*([^;}\n]+)/gi;
const RADIUS_RE = /border-radius\s*:\s*([^;}\n]+)/gi;
// JSX intrinsic-looking element that matches a registry component name (PascalCase).
function buildJsxRe(names) {
  if (!names.length) return null;
  const alt = names.map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  return new RegExp(`<\\s*(${alt})\\b`, 'g');
}

function add(out, cfg, rule, text, index, message, fix) {
  const s = sev(cfg, rule);
  if (s === 'off') return;
  const { line, col } = locate(text, index);
  out.push({ rule, severity: s, line, col, message, fix: fix || null });
}

/**
 * @param {string} filePath
 * @param {string} text
 * @param {object} cfg loaded config
 * @returns {Array<{rule,severity,line,col,message,fix}>}
 */
// The generated token file is the one place raw hex/rgba legitimately live.
const GENERATED_MARKER = 'generated by `strap tokens`';

export function scanFile(filePath, text, cfg) {
  const out = [];
  if (text.slice(0, 400).includes(GENERATED_MARKER)) return out;
  const isStyle = /\.(css|scss|sass|less)$/.test(filePath);
  const allowColors = new Set((cfg.allow.colors || []).map((c) => normalizeHex(c)));

  // 1. Raw hex colors -> must map to a token.
  let m;
  HEX_RE.lastIndex = 0;
  while ((m = HEX_RE.exec(text))) {
    const norm = normalizeHex(m[0]);
    if (allowColors.has(norm)) continue;
    const primitive = cfg.colorByHex.get(norm);
    if (primitive) {
      const suggestion = cfg.suggestByHex.get(norm) || primitive;
      add(out, cfg, 'rawHex', text, m.index,
        `Hardcoded ${m[0]} duplicates token "${suggestion}". Bind to the token/variable instead.`,
        suggestion);
    } else {
      add(out, cfg, 'rawHex', text, m.index,
        `Hardcoded color ${m[0]} is off-spec — no matching design token. Add a token or use the nearest approved one.`);
    }
  }

  // 2. rgb()/rgba() literals.
  RGB_RE.lastIndex = 0;
  while ((m = RGB_RE.exec(text))) {
    add(out, cfg, 'rawRgb', text, m.index,
      `Raw color ${m[0].replace(/\s+/g, ' ')} is off-spec. Reference a color token/variable.`);
  }

  // 3. font-family literals (only when a type system is defined — can't validate against nothing).
  FONT_FAMILY_RE.lastIndex = 0;
  while (cfg.fontSet.size && (m = FONT_FAMILY_RE.exec(text))) {
    const decl = m[1].trim();
    // Allow if it references a CSS variable / token.
    if (/var\(|\$|tokens?\.|theme\(|\{[a-z]+\.[a-zA-Z0-9]+/.test(decl)) continue;
    const first = decl.split(',')[0].replace(/['"]/g, '').trim().toLowerCase();
    if (first && !cfg.fontSet.has(first)) {
      add(out, cfg, 'rawFont', text, m.index + m[0].indexOf(m[1]),
        `Font "${first}" is not in the type system (${[...cfg.fontSet].join(', ') || 'none defined'}). Use a font token.`);
    }
  }

  // 4. Spacing px off the scale (style files only; needs a defined scale to check against).
  if (isStyle && cfg.spacingSet.size && sev(cfg, 'offScaleSpacing') !== 'off') {
    PX_RE.lastIndex = 0;
    while ((m = PX_RE.exec(text))) {
      const px = Number(m[1]);
      if ((cfg.allow.spacingPx || []).includes(px)) continue;
      // Skip px in declarations the spacing scale doesn't govern: radius, type sizing, borders.
      const lineStart = text.lastIndexOf('\n', m.index) + 1;
      const before = text.slice(lineStart, m.index);
      if (/border-radius|\bradius\b|font-size|line-height|letter-spacing|\bborder(?:-\w+)?\s*:/.test(before)) continue;
      if (!cfg.spacingSet.has(px)) {
        add(out, cfg, 'offScaleSpacing', text, m.index,
          `${m[0]} is not on the spacing scale [${[...cfg.spacingSet].join(', ')}]. Use a spacing token.`);
      }
    }
  }

  // 5. border-radius off the scale (needs a defined scale).
  if (cfg.radiusSet.size && sev(cfg, 'offScaleRadius') !== 'off') {
    RADIUS_RE.lastIndex = 0;
    while ((m = RADIUS_RE.exec(text))) {
      const val = m[1];
      if (/var\(|\$|tokens?\.|theme\(/.test(val)) continue;
      const pxm = /(\d+(?:\.\d+)?)px/.exec(val);
      if (pxm) {
        const r = Number(pxm[1]);
        if (r !== 0 && !cfg.radiusSet.has(r)) {
          add(out, cfg, 'offScaleRadius', text, m.index,
            `border-radius ${pxm[0]} is off the radius scale [${[...cfg.radiusSet].join(', ')}]. Use a radius token.`);
        }
      }
    }
  }

  // 6. Unlinked components: a registry component re-declared locally instead of imported.
  if (sev(cfg, 'unlinkedComponent') !== 'off' && cfg.registryNames.size) {
    // Only flag when the file LOCALLY defines a function/const with a registry name
    // (i.e. shadowing the design-system component instead of using the instance).
    for (const name of cfg.registryNames) {
      // Only enforce on component-like (PascalCase) names. Registries built from design specs
      // often use camelCase/lowercase names (buttonPrimary, field, chip) that collide with
      // ordinary local identifiers — flagging those would be noise, not signal.
      if (!/^[A-Z]/.test(name)) continue;
      // Skip the component's own source file — defining Button inside Button.tsx is correct.
      const src = cfg.sourceByName.get(name);
      if (src && filePath.replace(/\\/g, '/').endsWith(src.replace(/^\.?\//, ''))) continue;
      const defRe = new RegExp(`\\b(?:function|const|class)\\s+${name}\\b`, 'g');
      let d;
      while ((d = defRe.exec(text))) {
        const entry = (cfg.registry.components || []).find((c) => c.name === name);
        add(out, cfg, 'unlinkedComponent', text, d.index,
          `"${name}" is a Design System component (${entry?.import || entry?.figma || 'registry'}). Import the instance instead of redefining it.`,
          entry?.import || null);
      }
    }
  }

  return out;
}

export function maxSeverity(violations) {
  return violations.reduce((acc, v) => (SEV_RANK[v.severity] > SEV_RANK[acc] ? v.severity : acc), 'off');
}

export { SEV_RANK };
